version: '3.1'

services:

  wordpress:
    container_name: perros-wordpress
    image: wordpress:wp_perros_1.0
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ~/perrosweb/wordpress:/var/www/html

  db:
    container_name: perros-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/perrosweb/db:/var/lib/mysql
      
  phpmyadmin:
    container_name: perros-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:phpmyadmin_perros_1.0
    restart: "no"
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/perrosweb/php-myadmin:/var/www/html/phpmyadmin
